### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by marclelamy** [eddwebster/football_analytics#1]
In FBref Web Scraping and Parsing - 2020-2021 Season Only part 1.5.2.2 there's a 

`AttributeError                            Traceback (most recent call last)
<ipython-input-12-cb51c0aa74ec> in <module>
     14 
     15 ### Premier League
---> 16 df_fbref_team_premierleague_2021_raw = get_team_data('https://fbref.com/en/comps/9/10728/','/Premier-League-Stats')
     17 df_fbref_team_premierleague_2021_raw['league_name'] = 'Premier League'
     18 df_fbref_team_premierleague_2021_raw['league_country'] = 'England'

<ipython-input-11-1b0877df8a5d> in get_team_data(top, end)
      3     df1 = frame_for_category_team('stats',top,end,stats3)
      4     df2 = frame_for_category_team('keepers',top,end,keepers3)
----> 5     df3 = frame_for_category_team('keepersadv',top,end,keepersadv2)
      6     df4 = frame_for_category_team('shooting',top,end,shooting3)
      7     df5 = frame_for_category_team('passing',top,end,passing2)

<ipython-input-8-dd7769766814> in frame_for_category_team(category, top, end, features)
     75     url = (top + category + end)
     76     player_table, team_table = get_tables(url)
---> 77     df_team = get_frame_team(features, team_table)
     78     return df_team

<ipython-input-8-dd7769766814> in get_frame_team(features, team_table)
     53             for f in features_wanted_squad:
     54                 cell = row.find("td",{"data-stat": f})
---> 55                 a = cell.text.strip().encode()
     56                 text=a.decode("utf-8")
     57                 if(text == ''):

AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by eddwebster** [comment]
Thanks for raising this. From a quick observation, this is an error is from the code that I took from Parth Athale's 'Scrape-FBref-data' library here: https://github.com/parth1902/Scrape-FBref-data. This is most likely due to changes in the FBref website breaking the scraper.

I will take a look to see if Parth has updated his code to fix this. Thanks
